language: java
before_install:
- curl https://raw.github.com/liveSense/all/master/travis-settings.xml --create-dirs
  -o target/travis/settings.xml
jdk:
- openjdk6
script:
- mvn deploy --settings target/travis/settings.xml
env:
  global:
  - secure: M2ZTJdBdNNAdwfMma3TSlCkog2S9/0pLoqD0HUqixQxDsEdi/HicFjF2ZM5C/d/xaGK57x6WkZ/oBoRLb8hO6D1FxzdAydKRhrQ+5Nygtxblk0waZkx0+2t05EvT0yh+oo95clG8JQpGHpbHhX7/KN5fOrPGYLwrcbD4Z4iJdEA=
  - secure: SDdUd514fHk2UlWtUFRWKIxM5Ri7huO2suNrThiQvXp2UKPk3uDq5JQYxCxpYQPFA1Z5WpdCglYbKLCoU95uy5LvIS/xyWa5tjEbwRU25Wni1aM3q4aO+AFk03CoahccVPsTtq1Pb03V1p0ZajGGCrL5MOVw2kKnL3ktrTDJDso=
